[build]
builder = "nixpacks"
buildCommand = "pip install fastapi uvicorn python-dotenv groq requests numpy scikit-learn sentence-transformers"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"